version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command:  bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; alembic -c app/alembic.ini upgrade head; uvicorn app.main:app --host 0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 8000:8000
    environment:
      - SERVICE_DB_HOST=db
      - SERVICE_DB_USERNAME=admin
      - SERVICE_DB_PASSWORD=admin
      - SERVICE_DB_NAME=begemotic
      - SERVICE_DB_PORT=5432
    depends_on:
      - db

  db:
    image: postgis/postgis:15-3.3
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=begemotic

volumes:
  postgres_data: